version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 16
    labels:
      - dependabot
