repos:
  # black - code formatter
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  # flake8 - style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  # isort - import organizer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  # gitlint - git commit message linter
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
