name: Build infrastructure using getdeck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Getdeck
      run: |
        curl -sSL https://raw.githubusercontent.com/getdeck/getdeck/main/install.sh | sh -
    - name: Get the deck
      run: |
        deck get https://github.com/gefyrahq/gefyra-demos.git