# This workflow will build a PyOxidizer binary for Windows when a tag is pushed

name: Build Windows binary

env:
  PYOXIDIZER_DOWNLOAD: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.20.0/PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
    branches:
      - 'windows-port'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Determine App Version
      run: |
        python .github\scripts\get_version.py
        echo "${{ env.APP_VERSION }}"
    - name: Get pywin32
      run: |
        mkdir build 
        cd build
        git clone https://github.com/mhammond/pywin32.git
        cd pywin32
        git checkout b304
    - name: Setup PyOxidizer and build
      run: |
        Invoke-WebRequest 'https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.20.0/PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip' -OutFile .\PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip
        7z x PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip
        ls
        mkdir build\x86_64-pc-windows-msvc\release\install\
        ./pyoxidizer.exe build install --release
        ls .\build\x86_64-pc-windows-msvc\release\install\
        mkdir dist
        xcopy .\build\x86_64-pc-windows-msvc\release\install\* .\dist /s /e /k /i /y
        copy README.md ./dist/
        ls ./dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: getdeck-${{ env.APP_VERSION }}-x86_64-pc-windows
        path: |
          dist/
        retention-days: 5
    - name: Create release zip
      run: 7z a -r deck-${{ env.APP_VERSION }}-x86_64-pc-windows.zip "dist/"
    - name: Attach files to release
      uses: softprops/action-gh-release@v1
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: deck-${{ env.APP_VERSION }}-x86_64-pc-windows.zip