# This workflow will build Tooler's container images multi-arch

name: Build Container Images

# Controls when the workflow will run
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    tags:
      - "*"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      # Deck Tooler
      #
      - name: Tooler Image meta
        id: tooler_meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: |
            quay.io/getdeck/tooler
          tags: |
            type=raw,value=latest,enable=${{ !startsWith(github.ref, 'refs/tags/') }}
            type=raw,value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: tooler/
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tooler_meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/Getdeck/tooler:latest
          cache-to: type=registry,ref=quay.io/Getdeck/tooler:latest,mode=max
