name: black and flake8

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Lint and flake8 client
      run: |
        poetry install
        poetry run black . --check
        poetry run flake8 --config ../setup.cfg